config/routes.rb
Inventory::Application.routes.draw do
  get "welcome/index"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  resources :clothes
  root 'welcome#index'
  get 'clothes/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    if user
        can :access, :rails_admin
        can :dashboard
        if user.role? :clerk
            can :read, Clothe
            can :update, Clothe
        elsif user.role? :admin
            can :manage, :all 
        end
    end
  end
end

app/models/clothe.rb
class Clothe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :email, :password, :password_confirmation, :remember_me, :role

  def role_enum
  	%w[admin clerk]
  end

  def role?(role)
  	self.role == role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  #check_authorization
  #rescue_from CanCan::AccessDenied do |exception|
  #	redirect_to root_url, :alert => exception.message
  #end

end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource


  # GET /clothes
  # GET /clothes.json

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clothes/_form.html.erb
<%= form_for(@clothe) do |f| %>
  <% if @clothe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothe.errors.count, "error") %> prohibited this clothe from being saved:</h2>

      <ul>
      <% @clothe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clothes/edit.html.erb
<h1>Editing clothe</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothe %> |
<%= link_to 'Back', clothes_path %>

app/views/clothes/index.html.erb
<h1>Listing clothes</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clothes.each do |clothe| %>
      <tr>
        <td><%= clothe.item_id %></td>
        <td><%= clothe.title %></td>
        <td><%= clothe.quantity %></td>
        <td><%= clothe.price %></td>
        <td><%= link_to 'Show', clothe %></td>
        <td><%= link_to 'Edit', edit_clothe_path(clothe) %></td>
        <td><%= link_to 'Destroy', clothe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothe', new_clothe_path %>

app/views/clothes/new.html.erb
<h1>New clothe</h1>

<%= render 'form' %>

<%= link_to 'Back', clothes_path %>

app/views/clothes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @clothe.item_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @clothe.title %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @clothe.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @clothe.price %>
</p>

<%= link_to 'Edit', edit_clothe_path(@clothe) %> |
<%= link_to 'Back', clothes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <center><strong>
 	<%= link_to "Home", root_path%>
 	
	<% if user_signed_in? %>
	<a href="/admin"> Inventory</a>
	  Logged in as <%= current_user.email %>.
	  <%= link_to ' Edit profile', edit_user_registration_path %> |
	  <%= link_to " Logout", destroy_user_session_path, method: :delete %>
	<% else %>
	  <%= link_to " Sign up", new_user_registration_path  %> |
	  <%= link_to " Clerk Login", new_user_session_path  %>
	  <a href="/admin"> Admin Login</a>

	<% end %>
</strong></center>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<center>
	<h1>Inventory Management System</h1>
</center>